#!/usr/bin/env python3

"""
Utilities for generating whole-slide ABMIL attention heatmaps.

This module is model independent and can be used for attention
generated by either:
    - CTE stage classification
    - snRNA-seq target regression

Attention coordinates are converted from the coordinate-generation
resolution (for example, 0.5 mpp)

Alignment was corrected to process 20x and 40x slides .
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import openslide
import pandas as pd


DEFAULT_HEATMAP_MAX_DIM = 1800


def save_attention_heatmap(
    attention_df: pd.DataFrame,
    slide_path: str,
    heatmap_output_path: Path,
    raw_thumbnail_output_path: Path,
    title: str,
    max_dim: int = DEFAULT_HEATMAP_MAX_DIM,
) -> None:
    """
    Save a whole-slide thumbnail with tile attention overlaid.

    Parameters
    ----------
    attention_df:
        Tile-level dataframe containing:
            x_start
            y_start
            tile_width
            tile_height
            resolution
            units
            attention_score

    slide_path:
        Path to the original WSI.

    heatmap_output_path:
        Path where the attention heatmap PNG will be saved.

    raw_thumbnail_output_path:
        Path where the raw WSI thumbnail will be saved.

    title:
        Figure title.

    max_dim:
        Maximum dimension of the generated WSI thumbnail.

    Notes
    -----
    Coordinates are assumed to represent pixels at the physical
    resolution recorded in the `resolution` column.

    They must therefore be converted to OpenSlide level-0 coordinates
    before being mapped onto the thumbnail.
    """

    required_columns = {
        "x_start",
        "y_start",
        "tile_width",
        "tile_height",
        "resolution",
        "units",
        "attention_score",
    }

    missing = required_columns.difference(
        attention_df.columns
    )

    if missing:
        raise ValueError(
            "Attention dataframe is missing required columns: "
            f"{sorted(missing)}"
        )

    slide = openslide.OpenSlide(
        str(slide_path)
    )

    try:
        slide_width, slide_height = (
            slide.dimensions
        )

        # ---------------------------------------------------------
        # Read native level-0 physical resolution.
        # ---------------------------------------------------------

        mpp_x_value = slide.properties.get(
            openslide.PROPERTY_NAME_MPP_X
        )

        mpp_y_value = slide.properties.get(
            openslide.PROPERTY_NAME_MPP_Y
        )

        if (
            mpp_x_value is None
            or mpp_y_value is None
        ):
            raise ValueError(
                f"{slide_path}: OpenSlide does not "
                "provide MPP metadata. Cannot safely "
                "create an aligned attention heatmap."
            )

        slide_mpp_x = float(
            mpp_x_value
        )

        slide_mpp_y = float(
            mpp_y_value
        )

        # ---------------------------------------------------------
        # Confirm one coordinate resolution.
        # ---------------------------------------------------------

        coordinate_resolutions = (
            pd.to_numeric(
                attention_df["resolution"],
                errors="coerce",
            )
            .dropna()
            .unique()
        )

        if len(coordinate_resolutions) != 1:
            raise ValueError(
                f"{slide_path}: expected one "
                "coordinate resolution, but found "
                f"{coordinate_resolutions}."
            )

        coordinate_mpp = float(
            coordinate_resolutions[0]
        )

        coordinate_units = (
            attention_df["units"]
            .astype(str)
            .str.lower()
            .str.strip()
            .unique()
        )

        if (
            len(coordinate_units) != 1
            or coordinate_units[0] != "mpp"
        ):
            raise ValueError(
                f"{slide_path}: expected "
                "coordinate units='mpp', but found "
                f"{coordinate_units}."
            )

        # ---------------------------------------------------------
        # IMPORTANT:
        # Convert coordinate-frame pixels to level-0 pixels.
        #
        # This is the correction needed when coordinates generated
        # at e.g. 0.5 mpp are used with slides whose native MPP
        # differs, including 40x slides.
        # ---------------------------------------------------------

        coordinate_to_level0_x = (
            coordinate_mpp
            / slide_mpp_x
        )

        coordinate_to_level0_y = (
            coordinate_mpp
            / slide_mpp_y
        )

        x_start_level0 = (
            attention_df[
                "x_start"
            ].to_numpy(dtype=float)
            * coordinate_to_level0_x
        )

        y_start_level0 = (
            attention_df[
                "y_start"
            ].to_numpy(dtype=float)
            * coordinate_to_level0_y
        )

        tile_width_level0 = (
            attention_df[
                "tile_width"
            ].to_numpy(dtype=float)
            * coordinate_to_level0_x
        )

        tile_height_level0 = (
            attention_df[
                "tile_height"
            ].to_numpy(dtype=float)
            * coordinate_to_level0_y
        )

        # ---------------------------------------------------------
        # Create raw WSI thumbnail.
        # ---------------------------------------------------------

        requested_scale = min(
            max_dim / slide_width,
            max_dim / slide_height,
            1.0,
        )

        requested_thumbnail_size = (
            max(
                1,
                int(
                    round(
                        slide_width
                        * requested_scale
                    )
                ),
            ),
            max(
                1,
                int(
                    round(
                        slide_height
                        * requested_scale
                    )
                ),
            ),
        )

        thumbnail = (
            slide
            .get_thumbnail(
                requested_thumbnail_size
            )
            .convert("RGB")
        )

        raw_thumbnail_output_path = Path(
            raw_thumbnail_output_path
        )

        raw_thumbnail_output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        thumbnail.save(
            raw_thumbnail_output_path
        )

        print(
            "Saved raw WSI thumbnail:\n"
            f"{raw_thumbnail_output_path}"
        )

        # ---------------------------------------------------------
        # Use the actual returned thumbnail dimensions.
        # ---------------------------------------------------------

        thumbnail_scale_x = (
            thumbnail.width
            / slide_width
        )

        thumbnail_scale_y = (
            thumbnail.height
            / slide_height
        )

        # ---------------------------------------------------------
        # Map corrected level-0 coordinates onto the thumbnail.
        # ---------------------------------------------------------

        x_center = (
            x_start_level0
            + tile_width_level0 / 2.0
        ) * thumbnail_scale_x

        y_center = (
            y_start_level0
            + tile_height_level0 / 2.0
        ) * thumbnail_scale_y

        tile_width_thumbnail = (
            tile_width_level0
            * thumbnail_scale_x
        )

        tile_height_thumbnail = (
            tile_height_level0
            * thumbnail_scale_y
        )

        median_marker_width = float(
            np.nanmedian(
                tile_width_thumbnail
            )
        )

        median_marker_height = float(
            np.nanmedian(
                tile_height_thumbnail
            )
        )

        marker_area = max(
            median_marker_width
            * median_marker_height,
            1.0,
        )

        # ---------------------------------------------------------
        # Coordinate diagnostics.
        # ---------------------------------------------------------

        outside_count = int(
            np.sum(
                (x_start_level0 < 0)
                | (
                    x_start_level0
                    >= slide_width
                )
                | (y_start_level0 < 0)
                | (
                    y_start_level0
                    >= slide_height
                )
            )
        )

        if outside_count > 0:
            print(
                f"WARNING: {outside_count:,}/"
                f"{len(attention_df):,} corrected "
                "coordinates fall outside "
                f"{slide_path}."
            )

        print(
            "\nAttention heatmap coordinate "
            "diagnostics"
        )

        print(
            "--------------------------------"
        )

        print(
            f"Slide: {slide_path}"
        )

        print(
            "Level-0 dimensions: "
            f"{slide_width:,} x "
            f"{slide_height:,}"
        )

        print(
            "Level-0 MPP: "
            f"x={slide_mpp_x:.6f}, "
            f"y={slide_mpp_y:.6f}"
        )

        print(
            "Coordinate MPP: "
            f"{coordinate_mpp:.6f}"
        )

        print(
            "Coordinate-to-level-0 scale: "
            f"x={coordinate_to_level0_x:.4f}, "
            f"y={coordinate_to_level0_y:.4f}"
        )

        # ---------------------------------------------------------
        # Plot heatmap.
        # ---------------------------------------------------------

        plt.figure(
            figsize=(
                max(
                    6,
                    thumbnail.width / 250,
                ),
                max(
                    6,
                    thumbnail.height / 250,
                ),
            )
        )

        plt.imshow(
            thumbnail,
            extent=(
                0,
                thumbnail.width,
                thumbnail.height,
                0,
            ),
        )

        scatter = plt.scatter(
            x_center,
            y_center,
            c=attention_df[
                "attention_score"
            ].to_numpy(dtype=float),
            s=marker_area,
            marker="s",
            alpha=0.55,
            linewidths=0,
            cmap="viridis",
        )

        plt.xlim(
            0,
            thumbnail.width,
        )

        plt.ylim(
            thumbnail.height,
            0,
        )

        plt.colorbar(
            scatter,
            label="Attention score",
        )

        plt.title(title)
        plt.axis("off")
        plt.tight_layout()

        heatmap_output_path = Path(
            heatmap_output_path
        )

        heatmap_output_path.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        plt.savefig(
            heatmap_output_path,
            dpi=300,
            bbox_inches="tight",
        )

        plt.close()

    finally:
        slide.close()