#!/usr/bin/env python3

"""
ABMIL classification for Low-vs-High CTE stage prediction from UNI2 whole-slide histology embeddings.

Current implementation:
    - Supports one embedding file / WSI per donor.
    - Uses donor-grouped stratified cross-validation.
    - Selects checkpoint with highest validation Macro-F1.
    - Does not yet combine multiple embedding files or stains per donor.

Figures are generated by:
    - visualization/attention_heatmaps.py
    - visualization/high_attention_tiles.py
    - visualization/confusion_matrix.py
    - visualization/roc_curve.py

Example Run:
    python src/modeling/abmil_cte_stage_classification.py \
        --metadata /path/to/modeling_metadata.csv \
        --output-dir /path/to/results/stage_classification \
        --stain AT8 \
        --coordinate-source native \
        --target-name low_vs_high \

Run with --help to see all available options.
"""

############################## Imports ##############################

from __future__ import annotations
import argparse
import copy
import json
import random
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_ROOT))

import numpy as np
import pandas as pd
import torch
from sklearn.metrics import accuracy_score, f1_score
from sklearn.model_selection import StratifiedGroupKFold
from torch import nn
from torch.utils.data import DataLoader, Dataset

from src.modeling.cte_abmil import ABMILClassifier
from src.visualization.attention_heatmaps import save_attention_heatmap
from src.visualization.high_attention_tiles import save_top_attention_tiles
from src.visualization.classification_confusion_matrix import save_classification_summary
from src.visualization.classification_roc_curve import save_roc_outputs


DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
BATCH_SIZE = 1


############################## Arguments ##############################

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train binary ABMIL CTE stage classification from WSI embeddings."
    )

    # Input/output
    parser.add_argument("--metadata", type=Path, required=True,
                        help="Modeling metadata CSV.")
    parser.add_argument("--output-dir", type=Path, required=True,
                        help="Base directory for classification results.")

    # Experiment description
    parser.add_argument("--stain", required=True,
                        help="Histology stain used as model input, e.g. AT8, IBA1, LHE.")
    parser.add_argument("--target-name", default="low_vs_high",
                        help="Description of the classification target.")
    parser.add_argument("--coordinate-source", default=None,
                        help="Optional coordinate source, e.g. native or transferred_from_lhe.")
    parser.add_argument("--filter-name", default=None,
                        help="Optional filtering description, e.g. white080.")
    parser.add_argument("--run-name", default="",
                        help="Optional experiment/run description.")

    # Metadata/class definition
    parser.add_argument("--label-column", default="cte_label",
                        help="Metadata column containing class names.")
    parser.add_argument("--low-label", default="Low",
                        help="Label mapped to class 0.")
    parser.add_argument("--high-label", default="High",
                        help="Label mapped to class 1.")

    # Training
    parser.add_argument("--epochs", type=int, default=20)
    parser.add_argument("--learning-rate", type=float, default=1e-4)
    parser.add_argument("--n-splits", type=int, default=5)
    parser.add_argument("--seed", type=int, default=12)

    # Model
    parser.add_argument("--input-dim", type=int, default=1536)
    parser.add_argument("--hidden-dim", type=int, default=256)
    parser.add_argument("--dropout", type=float, default=0.25)

    # Attention
    parser.add_argument("--top-k", type=int, default=20)
    parser.add_argument("--no-attention", action="store_true",
                        help="Skip attention CSVs, top tiles, and heatmaps.")

    return parser.parse_args()


############################## Output Setup ##############################

def safe_name(name: str) -> str:
    return "".join(c if c.isalnum() or c in "_-" else "_" for c in name)


def create_output_dirs(args: argparse.Namespace) -> dict[str, Path]:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    results_dir = args.output_dir / safe_name(args.stain.upper())

    if args.coordinate_source:
        results_dir /= safe_name(args.coordinate_source)

    if args.filter_name:
        results_dir /= safe_name(args.filter_name)

    results_dir /= safe_name(args.target_name)
    results_dir /= f"{safe_name(args.run_name)}_{timestamp}"

    paths = {
        "results": results_dir,
        "attention": results_dir / "attention_scores",
        "top_tiles": results_dir / "top_attention_tiles",
        "heatmaps": results_dir / "attention_heatmaps",
        "checkpoints": results_dir / "checkpoints",
    }

    for path in paths.values():
        path.mkdir(parents=True, exist_ok=True)

    return paths


def save_run_config(args: argparse.Namespace, results_dir: Path) -> None:
    config = vars(args).copy()
    config["metadata"] = str(config["metadata"])
    config["output_dir"] = str(config["output_dir"])
    config["command"] = " ".join(sys.argv)
    config["device"] = str(DEVICE)

    with open(results_dir / "run_config.json", "w") as handle:
        json.dump(config, handle, indent=4)


############################## Reproducibility ##############################

def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed(seed)
        torch.cuda.manual_seed_all(seed)


############################## Metadata ##############################

def load_metadata(
    metadata_csv: Path,
    label_column: str,
    low_label: str,
    high_label: str,
) -> pd.DataFrame:
    """Load metadata and map Low/High class names to 0/1."""

    if not metadata_csv.exists():
        raise FileNotFoundError(f"Metadata file was not found:\n{metadata_csv}")

    df = pd.read_csv(metadata_csv)

    required = {
        "donor_id",
        "slide_id",
        "embedding_file",
        "coord_csv",
        "slide_path",
        label_column,
    }

    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"Metadata is missing required columns: {sorted(missing)}")

    df = df.dropna(subset=list(required)).copy()

    label_map = {
        low_label: 0,
        high_label: 1,
    }

    df["class_id"] = df[label_column].map(label_map)
    df = df.dropna(subset=["class_id"]).copy()
    df["class_id"] = df["class_id"].astype(int)

    for column in ["embedding_file", "coord_csv", "slide_path"]:
        df[column] = df[column].astype(str)

    embedding_exists = df["embedding_file"].apply(lambda path: Path(path).exists())

    if not embedding_exists.all():
        missing_paths = df.loc[~embedding_exists, "embedding_file"].tolist()
        print(f"\nWarning: {len(missing_paths)} embedding files were not found.")

        for path in missing_paths[:10]:
            print(f"  Missing: {path}")

        df = df.loc[embedding_exists].copy()

    print("\nBinary class mapping:")
    print(label_map)

    print("\nSamples retained:")
    print(df[label_column].value_counts())
    print(f"Unique donors retained: {df['donor_id'].nunique()}")

    return df.reset_index(drop=True)


def compute_class_weights(train_df: pd.DataFrame, num_classes: int = 2) -> torch.Tensor:
    """Compute balanced inverse-frequency weights from the training fold only."""

    class_counts = (
        train_df["class_id"]
        .value_counts()
        .reindex(range(num_classes), fill_value=0)
        .sort_index()
    )

    if (class_counts == 0).any():
        missing_classes = class_counts[class_counts == 0].index.tolist()
        raise ValueError(
            f"Training fold is missing class IDs: {missing_classes}. "
            f"Counts: {class_counts.to_dict()}"
        )

    total_samples = class_counts.sum()
    weights = total_samples / (num_classes * class_counts.astype(float))

    return torch.tensor(weights.to_numpy(), dtype=torch.float32)


############################## Dataset ##############################

class WSIBagDataset(Dataset):
    """One WSI embedding bag and one binary class label."""

    def __init__(self, metadata_df: pd.DataFrame, input_dim: int):
        self.df = metadata_df.reset_index(drop=True)
        self.input_dim = input_dim

    def __len__(self) -> int:
        return len(self.df)

    def __getitem__(self, idx: int):
        row = self.df.iloc[idx]
        embedding_path = Path(row["embedding_file"])
        loaded = torch.load(embedding_path, map_location="cpu")

        if "embeddings" not in loaded:
            raise KeyError(f"'embeddings' was not found in {embedding_path}")

        tile_embeddings = loaded["embeddings"].float()

        if tile_embeddings.ndim != 2:
            raise ValueError(
                f"Expected 2D embeddings for {row['donor_id']}, "
                f"received {tuple(tile_embeddings.shape)}"
            )

        if tile_embeddings.shape[1] != self.input_dim:
            raise ValueError(
                f"Expected embedding dimension {self.input_dim}, "
                f"but {row['donor_id']} has {tile_embeddings.shape[1]}"
            )

        label = torch.tensor(row["class_id"], dtype=torch.long)

        return (
            tile_embeddings,
            label,
            str(row["donor_id"]),
            str(row["slide_id"]),
            str(row["coord_csv"]),
            str(row["slide_path"]),
            str(row["embedding_file"]),
        )


############################## Training ##############################

def train_one_epoch(model, dataloader, criterion, optimizer, device) -> float:
    model.train()
    total_loss = 0.0

    for tile_embeddings, label, *_ in dataloader:
        tile_embeddings = tile_embeddings.squeeze(0).to(device)
        label = label.to(device)

        optimizer.zero_grad()
        logits, _ = model(tile_embeddings)

        loss = criterion(logits.unsqueeze(0), label)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(dataloader)


############################## Attention Outputs ##############################

def save_attention_outputs(
    donor_id: str,
    slide_id: str,
    coord_csv: str,
    slide_path: str,
    attention_scores: np.ndarray,
    true_label: int,
    pred_label: int,
    prob_high: float,
    fold_number: int,
    selected_epoch: int,
    checkpoint_type: str,
    output_dirs: dict[str, Path],
    top_k: int,
) -> dict:
    """Align attention to tile coordinates and create spatial outputs."""

    coord_df = pd.read_csv(coord_csv)

    defaults = {
        "tile_width": 256,
        "tile_height": 256,
        "resolution": 0.5,
        "units": "mpp",
    }

    for column, value in defaults.items():
        if column not in coord_df.columns:
            coord_df[column] = value

    attention_scores = np.asarray(attention_scores).reshape(-1)

    if len(coord_df) != len(attention_scores):
        raise ValueError(
            f"{slide_id}: {len(coord_df)} coordinate rows but "
            f"{len(attention_scores)} attention scores."
        )

    coord_df["attention_score"] = attention_scores
    coord_df["donor_id"] = donor_id
    coord_df["slide_id"] = slide_id
    coord_df["slide_path"] = slide_path
    coord_df["coord_csv"] = coord_csv
    coord_df["true_label"] = true_label
    coord_df["pred_label"] = pred_label
    coord_df["prob_low"] = 1.0 - prob_high
    coord_df["prob_high"] = prob_high
    coord_df["fold"] = fold_number
    coord_df["checkpoint_type"] = checkpoint_type
    coord_df["selected_epoch"] = selected_epoch

    # Save tile-level attention scores.
    fold_attention_dir = (
        output_dirs["attention"]
        / f"fold_{fold_number}"
        / checkpoint_type
    )
    fold_attention_dir.mkdir(parents=True, exist_ok=True)

    attention_csv = (
        fold_attention_dir
        / f"{donor_id}_{slide_id}_attention_scores.csv"
    )
    coord_df.to_csv(attention_csv, index=False)

    # Preserve classification's original coordinate-reading behavior.
    tile_dir = (
        output_dirs["top_tiles"]
        / f"fold_{fold_number}"
        / checkpoint_type
        / donor_id
        / slide_id
    )

    top_tile_summary = (
        fold_attention_dir
        / f"{donor_id}_{slide_id}_top_tiles_summary.csv"
    )

    save_top_attention_tiles(
        attention_df=coord_df,
        slide_path=slide_path,
        tile_output_dir=tile_dir,
        summary_output_path=top_tile_summary,
        top_k=top_k,
        coordinate_mode="resolution",
    )

    heatmap_dir = (
        output_dirs["heatmaps"]
        / f"fold_{fold_number}"
        / checkpoint_type
        / donor_id
    )
    heatmap_dir.mkdir(parents=True, exist_ok=True)

    raw_thumbnail = heatmap_dir / f"{slide_id}_raw_thumbnail.png"
    heatmap = heatmap_dir / f"{slide_id}_attention_heatmap.png"

    save_attention_heatmap(
        attention_df=coord_df,
        slide_path=slide_path,
        heatmap_output_path=heatmap,
        raw_thumbnail_output_path=raw_thumbnail,
        title=(
            f"{donor_id} | {slide_id} | "
            f"True: {true_label} | Pred: {pred_label}"
        ),
    )

    return {
        "attention_csv": str(attention_csv),
        "top_tile_summary_csv": str(top_tile_summary),
        "raw_thumbnail_png": str(raw_thumbnail),
        "heatmap_png": str(heatmap),
    }


############################## Evaluation ##############################

def evaluate(
    model,
    dataloader,
    criterion,
    device,
    output_dirs,
    top_k,
    save_attention=False,
    fold_number=None,
    selected_epoch=None,
    checkpoint_type=None,
):
    model.eval()

    total_loss = 0.0
    true_labels = []
    pred_labels = []
    prob_high_scores = []
    evaluated_slide_ids = []
    attention_outputs = []

    with torch.no_grad():
        for (
            tile_embeddings,
            label,
            donor_id,
            slide_id,
            coord_csv,
            slide_path,
            embedding_file,
        ) in dataloader:

            donor_id = donor_id[0]
            slide_id = slide_id[0]
            coord_csv = coord_csv[0]
            slide_path = slide_path[0]
            embedding_file = embedding_file[0]

            tile_embeddings = tile_embeddings.squeeze(0).to(device)
            label = label.to(device)

            logits, attention_weights = model(tile_embeddings)
            loss = criterion(logits.unsqueeze(0), label)

            # Class 1 is High CTE.
            class_probabilities = torch.softmax(logits, dim=0)
            prob_high = class_probabilities[1].item()
            pred = torch.argmax(logits).item()

            total_loss += loss.item()
            true_labels.append(label.item())
            pred_labels.append(pred)
            prob_high_scores.append(prob_high)
            evaluated_slide_ids.append(slide_id)

            if save_attention:
                attention_scores = (
                    attention_weights.detach().cpu().numpy().reshape(-1)
                )

                attention_paths = save_attention_outputs(
                    donor_id=donor_id,
                    slide_id=slide_id,
                    coord_csv=coord_csv,
                    slide_path=slide_path,
                    attention_scores=attention_scores,
                    true_label=label.item(),
                    pred_label=pred,
                    prob_high=prob_high,
                    fold_number=fold_number,
                    selected_epoch=selected_epoch,
                    checkpoint_type=checkpoint_type,
                    output_dirs=output_dirs,
                    top_k=top_k,
                )

                attention_outputs.append({
                    "donor_id": donor_id,
                    "slide_id": slide_id,
                    "coord_csv": coord_csv,
                    "slide_path": slide_path,
                    "embedding_file": embedding_file,
                    "true_label": label.item(),
                    "pred_label": pred,
                    "prob_high": prob_high,
                    **attention_paths,
                })

    if len(dataloader) == 0:
        raise ValueError("Cannot evaluate an empty dataloader.")

    avg_loss = total_loss / len(dataloader)
    accuracy = accuracy_score(true_labels, pred_labels)
    macro_f1 = f1_score(true_labels, pred_labels, average="macro")
    per_class_f1 = f1_score(
        true_labels,
        pred_labels,
        average=None,
        labels=[0, 1],
    )

    return (
        avg_loss,
        accuracy,
        macro_f1,
        per_class_f1,
        true_labels,
        pred_labels,
        prob_high_scores,
        evaluated_slide_ids,
        attention_outputs,
    )


############################## Cross Validation ##############################

def run_cross_validation(
    df: pd.DataFrame,
    args: argparse.Namespace,
    output_dirs: dict[str, Path],
):
    splitter = StratifiedGroupKFold(
        n_splits=args.n_splits,
        shuffle=True,
        random_state=args.seed,
    )

    fold_metrics = []
    all_predictions = []
    fold_assignments = []

    for fold, (train_idx, val_idx) in enumerate(
        splitter.split(
            df,
            y=df["class_id"],
            groups=df["donor_id"],
        ),
        start=1,
    ):
        print("\n" + "=" * 60)
        print(f"Starting fold {fold}")
        print("=" * 60)

        train_df = df.iloc[train_idx].reset_index(drop=True)
        val_df = df.iloc[val_idx].reset_index(drop=True)

        for _, row in val_df.iterrows():
            fold_assignments.append({
                "fold": fold,
                "donor_id": row["donor_id"],
                "slide_id": row["slide_id"],
                "class_id": row["class_id"],
            })

        print("Train class counts:")
        print(train_df[args.label_column].value_counts())

        print("\nValidation class counts:")
        print(val_df[args.label_column].value_counts())

        train_dataset = WSIBagDataset(train_df, args.input_dim)
        val_dataset = WSIBagDataset(val_df, args.input_dim)

        train_loader = DataLoader(
            train_dataset,
            batch_size=BATCH_SIZE,
            shuffle=True,
            num_workers=0,
        )

        val_loader = DataLoader(
            val_dataset,
            batch_size=BATCH_SIZE,
            shuffle=False,
            num_workers=0,
        )

        model = ABMILClassifier(
            input_dim=args.input_dim,
            hidden_dim=args.hidden_dim,
            num_classes=2,
            dropout=args.dropout,
        ).to(DEVICE)

        class_weights = compute_class_weights(train_df, num_classes=2).to(DEVICE)

        print("\nClass weights:")
        print(class_weights)

        criterion = nn.CrossEntropyLoss(weight=class_weights)
        optimizer = torch.optim.Adam(
            model.parameters(),
            lr=args.learning_rate,
        )

        best_val_f1 = -float("inf")
        best_epoch = None
        best_model_state = None
        training_history = []

        for epoch in range(1, args.epochs + 1):
            train_loss = train_one_epoch(
                model,
                train_loader,
                criterion,
                optimizer,
                DEVICE,
            )

            (
                val_loss,
                val_acc,
                val_f1,
                per_class_f1,
                _,
                _,
                _,
                _,
                _,
            ) = evaluate(
                model=model,
                dataloader=val_loader,
                criterion=criterion,
                device=DEVICE,
                output_dirs=output_dirs,
                top_k=args.top_k,
                save_attention=False,
            )

            training_history.append({
                "fold": fold,
                "epoch": epoch,
                "train_loss": train_loss,
                "val_loss": val_loss,
                "val_accuracy": val_acc,
                "val_macro_f1": val_f1,
            })

            print(
                f"Fold {fold} | Epoch {epoch:03d}/{args.epochs} | "
                f"Train Loss: {train_loss:.4f} | "
                f"Val Loss: {val_loss:.4f} | "
                f"Val Acc: {val_acc:.4f} | "
                f"Val Macro-F1: {val_f1:.4f}"
            )

            if val_f1 > best_val_f1:
                best_val_f1 = val_f1
                best_epoch = epoch
                best_model_state = copy.deepcopy(model.state_dict())

        if best_model_state is None:
            raise RuntimeError(
                f"No best Macro-F1 checkpoint was selected for fold {fold}"
            )

        model.load_state_dict(best_model_state)

        print(
            f"\nExporting held-out predictions/attention for fold {fold}, "
            f"best epoch {best_epoch}"
        )

        (
            final_val_loss,
            final_val_acc,
            final_val_f1,
            final_per_class_f1,
            final_y_true,
            final_y_pred,
            final_prob_high,
            final_slide_ids,
            _,
        ) = evaluate(
            model=model,
            dataloader=val_loader,
            criterion=criterion,
            device=DEVICE,
            output_dirs=output_dirs,
            top_k=args.top_k,
            save_attention=not args.no_attention,
            fold_number=fold,
            selected_epoch=best_epoch,
            checkpoint_type="highest_macro_f1",
        )

        if not (
            len(final_slide_ids)
            == len(final_y_true)
            == len(final_y_pred)
            == len(final_prob_high)
        ):
            raise ValueError(f"Fold {fold}: evaluation outputs have different lengths.")

        if len(final_slide_ids) != len(val_df):
            raise ValueError(
                f"Fold {fold}: evaluated {len(final_slide_ids)} slides, "
                f"but validation metadata contains {len(val_df)}."
            )

        if len(set(final_slide_ids)) != len(final_slide_ids):
            raise ValueError(f"Fold {fold}: duplicate validation slide IDs returned.")

        if not all(0.0 <= probability <= 1.0 for probability in final_prob_high):
            raise ValueError(f"Fold {fold}: probability outside [0, 1].")

        fold_metrics.append({
            "fold": fold,
            "best_epoch": best_epoch,
            "val_loss": final_val_loss,
            "val_accuracy": final_val_acc,
            "val_macro_f1": final_val_f1,
            "low_f1": final_per_class_f1[0],
            "high_f1": final_per_class_f1[1],
        })

        print("\nBest validation Macro-F1 checkpoint:")
        print(f"Epoch: {best_epoch}")
        print(f"Validation Loss: {final_val_loss:.4f}")
        print(f"Validation Accuracy: {final_val_acc:.4f}")
        print(f"Validation Macro-F1: {final_val_f1:.4f}")
        print(f"Low F1: {final_per_class_f1[0]:.4f}")
        print(f"High F1: {final_per_class_f1[1]:.4f}")

        val_metadata_by_slide = val_df.set_index("slide_id", drop=False)

        for slide_id, true_label, pred_label, prob_high in zip(
            final_slide_ids,
            final_y_true,
            final_y_pred,
            final_prob_high,
        ):
            if slide_id not in val_metadata_by_slide.index:
                raise ValueError(
                    f"Fold {fold}: evaluated slide {slide_id} was not found in val_df."
                )

            sample_row = val_metadata_by_slide.loc[slide_id]

            all_predictions.append({
                "fold": fold,
                "best_epoch": best_epoch,
                "donor_id": sample_row["donor_id"],
                "slide_id": slide_id,
                args.label_column: sample_row[args.label_column],
                "true_label": int(true_label),
                "pred_label": int(pred_label),
                "prob_low": float(1.0 - prob_high),
                "prob_high": float(prob_high),
            })

        pd.DataFrame(training_history).to_csv(
            output_dirs["results"] / f"fold_{fold}_training_history.csv",
            index=False,
        )

        torch.save(
            {
                "fold": fold,
                "best_epoch": best_epoch,
                "model_state_dict": best_model_state,
                "class_mapping": {
                    args.low_label: 0,
                    args.high_label: 1,
                },
                "model_config": {
                    "input_dim": args.input_dim,
                    "hidden_dim": args.hidden_dim,
                    "num_classes": 2,
                    "dropout": args.dropout,
                },
            },
            output_dirs["checkpoints"] / f"fold_{fold}_best_model.pt",
        )

    return fold_metrics, all_predictions, fold_assignments


############################## Save Results ##############################

def save_results(
    fold_metrics,
    all_predictions,
    fold_assignments,
    args: argparse.Namespace,
    output_dirs: dict[str, Path],
) -> None:
    results_dir = output_dirs["results"]

    metrics_df = pd.DataFrame(fold_metrics)
    predictions_df = pd.DataFrame(all_predictions)
    fold_assignments_df = pd.DataFrame(fold_assignments)

    print("\n" + "=" * 60)
    print("Overall Cross Validation Results")
    print("=" * 60)

    print(
        f"Mean Accuracy: {metrics_df['val_accuracy'].mean():.4f} ± "
        f"{metrics_df['val_accuracy'].std():.4f}"
    )
    print(
        f"Mean Macro-F1: {metrics_df['val_macro_f1'].mean():.4f} ± "
        f"{metrics_df['val_macro_f1'].std():.4f}"
    )
    print(
        f"Mean Low F1: {metrics_df['low_f1'].mean():.4f} ± "
        f"{metrics_df['low_f1'].std():.4f}"
    )
    print(
        f"Mean High F1: {metrics_df['high_f1'].mean():.4f} ± "
        f"{metrics_df['high_f1'].std():.4f}"
    )

    required = {
        "fold",
        "best_epoch",
        "donor_id",
        "slide_id",
        args.label_column,
        "true_label",
        "pred_label",
        "prob_low",
        "prob_high",
    }

    missing = required.difference(predictions_df.columns)
    if missing:
        raise ValueError(f"Prediction output is missing columns: {sorted(missing)}")

    if predictions_df["prob_high"].isna().any():
        raise ValueError("predictions.csv contains missing prob_high values.")

    if not predictions_df["prob_high"].between(0, 1).all():
        raise ValueError("predictions.csv contains prob_high values outside [0, 1].")

    if len(predictions_df) != len(fold_assignments_df):
        raise ValueError(
            "Prediction count does not match the number of held-out CV samples."
        )

    if predictions_df["slide_id"].duplicated().any():
        duplicated = predictions_df.loc[
            predictions_df["slide_id"].duplicated(keep=False),
            ["fold", "slide_id"],
        ]
        raise ValueError(
            "Some slides have more than one cross-validation prediction:\n"
            f"{duplicated}"
        )

    metrics_df.to_csv(results_dir / "fold_metrics.csv", index=False)
    predictions_df.to_csv(results_dir / "predictions.csv", index=False)
    fold_assignments_df.to_csv(results_dir / "fold_assignments.csv", index=False)

    class_names = [args.low_label, args.high_label]

    save_classification_summary(
        predictions_df=predictions_df,
        output_dir=results_dir,
        class_names=class_names,
    )

    pooled_auc = save_roc_outputs(
        predictions_df=predictions_df,
        output_dir=results_dir,
        stain=args.stain,
    )

    print("\nSaved results:")
    print(results_dir / "fold_metrics.csv")
    print(results_dir / "predictions.csv")
    print(results_dir / "fold_assignments.csv")
    print(results_dir / "confusion_matrix.png")
    print(results_dir / "classification_report.csv")
    print(results_dir / "roc_curve.png")
    print(results_dir / "roc_curve_points.csv")
    print(results_dir / "roc_auc_summary.csv")
    print(f"Pooled ROC-AUC: {pooled_auc:.4f}")


############################## Main ##############################

def main() -> None:
    args = parse_args()

    set_seed(args.seed)
    output_dirs = create_output_dirs(args)
    save_run_config(args, output_dirs["results"])

    print(f"Using device: {DEVICE}")
    print(f"Stain: {args.stain}")
    print(f"Classes: {args.low_label} = 0, {args.high_label} = 1")
    print(f"Results directory:\n{output_dirs['results']}")

    df = load_metadata(
        metadata_csv=args.metadata,
        label_column=args.label_column,
        low_label=args.low_label,
        high_label=args.high_label,
    )

    fold_metrics, all_predictions, fold_assignments = run_cross_validation(
        df,
        args,
        output_dirs,
    )

    save_results(
        fold_metrics,
        all_predictions,
        fold_assignments,
        args,
        output_dirs,
    )

    print("\nClassification modeling complete.")


if __name__ == "__main__":
    main()




